### ISSUE TITLE
use_as_react_component

### ISSUE THREAD

**Issue by ckdo8008** [kovacsv/Online3DViewerExample#4]
> o3dv.module.js:14323 
 Uncaught TypeError: edgeSettings.Clone is not a function
    at Viewer.SetEdgeSettings (o3dv.module.js:14323:1)
    at new EmbeddedViewer (o3dv.module.js:14750:1)
    at ViewerWithUrls.js:13:1
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)

    "online-3d-viewer": "^0.12.0" <------- Exception
    "online-3d-viewer": "^0.8.18" <------- Exception
    
Why does the example produce an error?

**Comment by kerimmandaci** [comment]
I am getting the same error. Any solution ?
